### ISSUE TITLE
yml files no longer work with Apexcards v2.1.2

### ISSUE THREAD

**Issue by andro42** [frlequ/mojelektro-apex-chart#2]
The look of the graph for 15 min data is like in the picture attached:
![image](https://github.com/user-attachments/assets/2da2652f-a9b2-45ab-8dd6-e97f91d2d457)

**Comment by frlequ** [comment]
Thanks for notice. There is a fix in the new version:

https://github.com/frlequ/mojelektro-apex-chart/blob/main/15min_interval_input.yaml
